defaults:
  - setup
  - obs_encoder: rgb
  - knl_decoder: default

_target_: t3vip.models.cdna.CDNA
_recursive_: false

alpha_rcr: ${loss.alpha_rcr}
alpha_kl: 0
alpha_l: ${loss.alpha_l}
reuse_first_rgb: false
stochastic: false
