defaults:
  - act_encoder: default
  - msk_decoder: default
  - distribution: continuous
  - optimizer: adam
  - lr_scheduler: none

intrinsics: ???
xygrid: ???
act_cond: true
num_context_frames: 2
time_invariant: false
gen_iters: 50000
