defaults:
  - setup
  - obs_encoder: rgb
  - knl_decoder: default
  - inference_net: default

_target_: t3vip.models.sv2p.SV2P
_recursive_: false

stochastic: true
alpha_rcr: ${loss.alpha_rcr}
alpha_kl: ${loss.alpha_kl}
alpha_l: ${loss.alpha_l}
reuse_first_rgb: true
