defaults:
  - setup
  - obs_encoder: rgbd
  - se3_decoder: default
  - rgbd_inpainter: default
  - inference_net: default

_target_: t3vip.models.t3vip.T3VIP
_recursive_: false

splat: average
stochastic: true
alpha_rcr: ${loss.alpha_rcr}
alpha_rcd: ${loss.alpha_rcd}
alpha_knn: ${loss.alpha_knn}
alpha_sfs: ${loss.alpha_sfs}
alpha_ofs: ${loss.alpha_ofs}
alpha_kl: ${loss.alpha_kl}
alpha_l: ${loss.alpha_l}
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}
