defaults:
  - setup
  - obs_encoder: rgbd
  - se3_decoder: default
  - rgbd_inpainter: default

_target_: t3vip.models.t3vip.T3VIP
_recursive_: false

splat: average
alpha_rcr: 0.65910719
alpha_rcd: 0.1645335
alpha_knn: 0.00307535
alpha_sfs: 0.0028537
alpha_ofs: 0.0020718
alpha_kl: 0.0
alpha_l: 2
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}
optimizer:
  lr: 0.000395717
