defaults:
  - setup
  - obs_encoder: rgbd
  - se3_decoder: default
  - rgbd_inpainter: default
  - inference_net: default

_target_: t3vip.models.t3vip.T3VIP
_recursive_: false

splat: average
stochastic: true
alpha_rcr: 0.7277019
alpha_rcd: 0.8205359
alpha_knn: 0.0131920
alpha_sfs: 0.0046617
alpha_ofs: 0.0022264
alpha_kl: 0.001
alpha_l: 1
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}
optimizer:
  lr: 0.0002814