defaults:
  - setup
  - obs_encoder: rgbd
  - se3_decoder: default
  - rgbd_inpainter: default
  - inference_net: default

_target_: t3vip.models.t3vip.T3VIP
_recursive_: false

splat: average
stochastic: true
alpha_rcr: 0.8618375
alpha_rcd: 0.0097064
alpha_knn: 0.4826188
alpha_sfs: 0.1265362
alpha_ofs: 0.0010007
alpha_kl: 0.001
alpha_l: 1
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}
optimizer:
  lr: 0.0000742