defaults:
  - setup
  - obs_encoder: rgbd
  - se3_decoder: default
  - rgbd_inpainter: default
  - inference_net: default

_target_: t3vip.models.t3vip.T3VIP
_recursive_: false

splat: average
stochastic: true
alpha_rcr: 0.4815314
alpha_rcd: 0.0723196
alpha_knn: 0.0158731
alpha_sfs: 0.0043173
alpha_ofs: 0.0038682
alpha_kl: 0.001
alpha_l: 2
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}
optimizer:
  lr: 0.0004699
