_target_: t3vip.models.inference.inference_net.QNet
chn: [32, 64, 64]
dims: [32, 16, 16, 8]
input_chn: ${model.obs_encoder.input_chn}
dim_latent: 8
seq_len: ${datamodule.seq_len}
min_logvar: -5.0
norm: ${model.obs_encoder.norm}
activation: ${model.obs_encoder.activation}
min_dpt: ${datamodule.dataset.min_dpt}
max_dpt: ${datamodule.dataset.max_dpt}